allowBuilds:
  '@swc/core': true
minimumReleaseAgeExclude:
  - '@typescript/typescript-darwin-arm64@7.1.0-dev.20261009.1'
  - '@typescript/typescript-darwin-x64@7.1.0-dev.20261009.1'
  - '@typescript/typescript-linux-arm64@7.1.0-dev.20261009.1'
  - '@typescript/typescript-linux-arm@7.1.0-dev.20261009.1'
  - '@typescript/typescript-linux-x64@7.1.0-dev.20261009.1'
  - '@typescript/typescript-win32-arm64@7.1.0-dev.20261009.1'
  - '@typescript/typescript-win32-x64@7.1.0-dev.20261009.1'
  - typescript@7.1.0-dev.20261009.1
