/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AiRouteImport } from './routes/ai'
import { Route as ComponentsRouteImport } from './routes/components'
import { Route as ConfigRouteImport } from './routes/config'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as HelpRouteImport } from './routes/help'
import { Route as PermissionsRouteImport } from './routes/permissions'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RecentsRouteImport } from './routes/recents'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as UsersRouteImport } from './routes/users'
import { Route as ViewsRouteImport } from './routes/views'
import { Route as WorkbooksRouteImport } from './routes/workbooks'
import { Route as ConfigIndexRouteImport } from './routes/config.index'
import { Route as ConfigSmtpRouteImport } from './routes/config.smtp'
import { Route as TTeamSlugRouteImport } from './routes/t.$teamSlug'
import { Route as TTeamSlugIndexRouteImport } from './routes/t.$teamSlug.index'
import { Route as TTeamSlugFavoritesRouteImport } from './routes/t.$teamSlug.favorites'
import { Route as TTeamSlugRecentsRouteImport } from './routes/t.$teamSlug.recents'
import { Route as TTeamSlugViewsRouteImport } from './routes/t.$teamSlug.views'
import { Route as TTeamSlugWorkbooksRouteImport } from './routes/t.$teamSlug.workbooks'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsRoute = ComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRoute = ConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const PermissionsRoute = PermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RecentsRoute = RecentsRouteImport.update({
  id: '/recents',
  path: '/recents',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewsRoute = ViewsRouteImport.update({
  id: '/views',
  path: '/views',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkbooksRoute = WorkbooksRouteImport.update({
  id: '/workbooks',
  path: '/workbooks',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigIndexRoute = ConfigIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConfigRoute,
} as any)
const ConfigSmtpRoute = ConfigSmtpRouteImport.update({
  id: '/smtp',
  path: '/smtp',
  getParentRoute: () => ConfigRoute,
} as any)
const TTeamSlugRoute = TTeamSlugRouteImport.update({
  id: '/t/$teamSlug',
  path: '/t/$teamSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const TTeamSlugIndexRoute = TTeamSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TTeamSlugRoute,
} as any)
const TTeamSlugFavoritesRoute = TTeamSlugFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => TTeamSlugRoute,
} as any)
const TTeamSlugRecentsRoute = TTeamSlugRecentsRouteImport.update({
  id: '/recents',
  path: '/recents',
  getParentRoute: () => TTeamSlugRoute,
} as any)
const TTeamSlugViewsRoute = TTeamSlugViewsRouteImport.update({
  id: '/views',
  path: '/views',
  getParentRoute: () => TTeamSlugRoute,
} as any)
const TTeamSlugWorkbooksRoute = TTeamSlugWorkbooksRouteImport.update({
  id: '/workbooks',
  path: '/workbooks',
  getParentRoute: () => TTeamSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/ai': typeof AiRoute
  '/components': typeof ComponentsRoute
  '/config': typeof ConfigRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/help': typeof HelpRoute
  '/permissions': typeof PermissionsRoute
  '/profile': typeof ProfileRoute
  '/recents': typeof RecentsRoute
  '/teams': typeof TeamsRoute
  '/users': typeof UsersRoute
  '/views': typeof ViewsRoute
  '/workbooks': typeof WorkbooksRoute
  '/config/smtp': typeof ConfigSmtpRoute
  '/t/$teamSlug': typeof TTeamSlugRouteWithChildren
  '/config/': typeof ConfigIndexRoute
  '/t/$teamSlug/favorites': typeof TTeamSlugFavoritesRoute
  '/t/$teamSlug/recents': typeof TTeamSlugRecentsRoute
  '/t/$teamSlug/views': typeof TTeamSlugViewsRoute
  '/t/$teamSlug/workbooks': typeof TTeamSlugWorkbooksRoute
  '/t/$teamSlug/': typeof TTeamSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/ai': typeof AiRoute
  '/components': typeof ComponentsRoute
  '/favorites': typeof FavoritesRoute
  '/help': typeof HelpRoute
  '/permissions': typeof PermissionsRoute
  '/profile': typeof ProfileRoute
  '/recents': typeof RecentsRoute
  '/teams': typeof TeamsRoute
  '/users': typeof UsersRoute
  '/views': typeof ViewsRoute
  '/workbooks': typeof WorkbooksRoute
  '/config/smtp': typeof ConfigSmtpRoute
  '/config': typeof ConfigIndexRoute
  '/t/$teamSlug/favorites': typeof TTeamSlugFavoritesRoute
  '/t/$teamSlug/recents': typeof TTeamSlugRecentsRoute
  '/t/$teamSlug/views': typeof TTeamSlugViewsRoute
  '/t/$teamSlug/workbooks': typeof TTeamSlugWorkbooksRoute
  '/t/$teamSlug': typeof TTeamSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/ai': typeof AiRoute
  '/components': typeof ComponentsRoute
  '/config': typeof ConfigRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/help': typeof HelpRoute
  '/permissions': typeof PermissionsRoute
  '/profile': typeof ProfileRoute
  '/recents': typeof RecentsRoute
  '/teams': typeof TeamsRoute
  '/users': typeof UsersRoute
  '/views': typeof ViewsRoute
  '/workbooks': typeof WorkbooksRoute
  '/config/smtp': typeof ConfigSmtpRoute
  '/t/$teamSlug': typeof TTeamSlugRouteWithChildren
  '/config/': typeof ConfigIndexRoute
  '/t/$teamSlug/favorites': typeof TTeamSlugFavoritesRoute
  '/t/$teamSlug/recents': typeof TTeamSlugRecentsRoute
  '/t/$teamSlug/views': typeof TTeamSlugViewsRoute
  '/t/$teamSlug/workbooks': typeof TTeamSlugWorkbooksRoute
  '/t/$teamSlug/': typeof TTeamSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/ai'
    | '/components'
    | '/config'
    | '/favorites'
    | '/help'
    | '/permissions'
    | '/profile'
    | '/recents'
    | '/teams'
    | '/users'
    | '/views'
    | '/workbooks'
    | '/config/smtp'
    | '/t/$teamSlug'
    | '/config/'
    | '/t/$teamSlug/favorites'
    | '/t/$teamSlug/recents'
    | '/t/$teamSlug/views'
    | '/t/$teamSlug/workbooks'
    | '/t/$teamSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/ai'
    | '/components'
    | '/favorites'
    | '/help'
    | '/permissions'
    | '/profile'
    | '/recents'
    | '/teams'
    | '/users'
    | '/views'
    | '/workbooks'
    | '/config/smtp'
    | '/config'
    | '/t/$teamSlug/favorites'
    | '/t/$teamSlug/recents'
    | '/t/$teamSlug/views'
    | '/t/$teamSlug/workbooks'
    | '/t/$teamSlug'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/ai'
    | '/components'
    | '/config'
    | '/favorites'
    | '/help'
    | '/permissions'
    | '/profile'
    | '/recents'
    | '/teams'
    | '/users'
    | '/views'
    | '/workbooks'
    | '/config/smtp'
    | '/t/$teamSlug'
    | '/config/'
    | '/t/$teamSlug/favorites'
    | '/t/$teamSlug/recents'
    | '/t/$teamSlug/views'
    | '/t/$teamSlug/workbooks'
    | '/t/$teamSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AiRoute: typeof AiRoute
  ComponentsRoute: typeof ComponentsRoute
  ConfigRoute: typeof ConfigRouteWithChildren
  FavoritesRoute: typeof FavoritesRoute
  HelpRoute: typeof HelpRoute
  PermissionsRoute: typeof PermissionsRoute
  ProfileRoute: typeof ProfileRoute
  RecentsRoute: typeof RecentsRoute
  TeamsRoute: typeof TeamsRoute
  UsersRoute: typeof UsersRoute
  ViewsRoute: typeof ViewsRoute
  WorkbooksRoute: typeof WorkbooksRoute
  TTeamSlugRoute: typeof TTeamSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components': {
      id: '/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permissions': {
      id: '/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof PermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recents': {
      id: '/recents'
      path: '/recents'
      fullPath: '/recents'
      preLoaderRoute: typeof RecentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/views': {
      id: '/views'
      path: '/views'
      fullPath: '/views'
      preLoaderRoute: typeof ViewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workbooks': {
      id: '/workbooks'
      path: '/workbooks'
      fullPath: '/workbooks'
      preLoaderRoute: typeof WorkbooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/': {
      id: '/config/'
      path: '/'
      fullPath: '/config/'
      preLoaderRoute: typeof ConfigIndexRouteImport
      parentRoute: typeof ConfigRoute
    }
    '/config/smtp': {
      id: '/config/smtp'
      path: '/smtp'
      fullPath: '/config/smtp'
      preLoaderRoute: typeof ConfigSmtpRouteImport
      parentRoute: typeof ConfigRoute
    }
    '/t/$teamSlug': {
      id: '/t/$teamSlug'
      path: '/t/$teamSlug'
      fullPath: '/t/$teamSlug'
      preLoaderRoute: typeof TTeamSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$teamSlug/': {
      id: '/t/$teamSlug/'
      path: '/'
      fullPath: '/t/$teamSlug/'
      preLoaderRoute: typeof TTeamSlugIndexRouteImport
      parentRoute: typeof TTeamSlugRoute
    }
    '/t/$teamSlug/favorites': {
      id: '/t/$teamSlug/favorites'
      path: '/favorites'
      fullPath: '/t/$teamSlug/favorites'
      preLoaderRoute: typeof TTeamSlugFavoritesRouteImport
      parentRoute: typeof TTeamSlugRoute
    }
    '/t/$teamSlug/recents': {
      id: '/t/$teamSlug/recents'
      path: '/recents'
      fullPath: '/t/$teamSlug/recents'
      preLoaderRoute: typeof TTeamSlugRecentsRouteImport
      parentRoute: typeof TTeamSlugRoute
    }
    '/t/$teamSlug/views': {
      id: '/t/$teamSlug/views'
      path: '/views'
      fullPath: '/t/$teamSlug/views'
      preLoaderRoute: typeof TTeamSlugViewsRouteImport
      parentRoute: typeof TTeamSlugRoute
    }
    '/t/$teamSlug/workbooks': {
      id: '/t/$teamSlug/workbooks'
      path: '/workbooks'
      fullPath: '/t/$teamSlug/workbooks'
      preLoaderRoute: typeof TTeamSlugWorkbooksRouteImport
      parentRoute: typeof TTeamSlugRoute
    }
  }
}

interface ConfigRouteChildren {
  ConfigSmtpRoute: typeof ConfigSmtpRoute
  ConfigIndexRoute: typeof ConfigIndexRoute
}

const ConfigRouteChildren: ConfigRouteChildren = {
  ConfigSmtpRoute: ConfigSmtpRoute,
  ConfigIndexRoute: ConfigIndexRoute,
}

const ConfigRouteWithChildren =
  ConfigRoute._addFileChildren(ConfigRouteChildren)

interface TTeamSlugRouteChildren {
  TTeamSlugFavoritesRoute: typeof TTeamSlugFavoritesRoute
  TTeamSlugRecentsRoute: typeof TTeamSlugRecentsRoute
  TTeamSlugViewsRoute: typeof TTeamSlugViewsRoute
  TTeamSlugWorkbooksRoute: typeof TTeamSlugWorkbooksRoute
  TTeamSlugIndexRoute: typeof TTeamSlugIndexRoute
}

const TTeamSlugRouteChildren: TTeamSlugRouteChildren = {
  TTeamSlugFavoritesRoute: TTeamSlugFavoritesRoute,
  TTeamSlugRecentsRoute: TTeamSlugRecentsRoute,
  TTeamSlugViewsRoute: TTeamSlugViewsRoute,
  TTeamSlugWorkbooksRoute: TTeamSlugWorkbooksRoute,
  TTeamSlugIndexRoute: TTeamSlugIndexRoute,
}

const TTeamSlugRouteWithChildren = TTeamSlugRoute._addFileChildren(
  TTeamSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AiRoute: AiRoute,
  ComponentsRoute: ComponentsRoute,
  ConfigRoute: ConfigRouteWithChildren,
  FavoritesRoute: FavoritesRoute,
  HelpRoute: HelpRoute,
  PermissionsRoute: PermissionsRoute,
  ProfileRoute: ProfileRoute,
  RecentsRoute: RecentsRoute,
  TeamsRoute: TeamsRoute,
  UsersRoute: UsersRoute,
  ViewsRoute: ViewsRoute,
  WorkbooksRoute: WorkbooksRoute,
  TTeamSlugRoute: TTeamSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
